apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.repository }}
  labels:
    app: {{ $.Values.image.repository }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.image.repository }}
  template:
    metadata:
      labels:
        app: {{ $.Values.image.repository }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
