apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}
  labels:
    app: {{ $.Values.image.repository }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }} 
      protocol: TCP
      name: test-gitops-port
  selector:
    app: {{ $.Values.image.repository }}
